---
title: "Initialize pinboard"
format: html
---

This subproject initializes pinboard required for the default `targets` project.

## Setup

### Targets environment for subproject

```{r}
#| label: define_project
#| include: false
Sys.setenv(TAR_PROJECT = "pinboard")
```

### Targets script setup

```{r}
#| label: setup
#| include: false
library(targets)
tar_unscript(script = "_pinboard.R")
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


### Targets globals

We first define some global options/functions common to all targets.

```{r}
#| engine: targets
#| label: globals
#| tar_globals: true

# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
tar_option_set(packages = packages())
```

## Pinboard setup

```{r}
#| engine: targets
#| label: pin_setup
list(
tar_target(
    name = cache_path,
    command = here::here("data", "data_raw"),
    format = "file"
),
tar_target(
    name = manifest_url,
    command = Sys.getenv("MANIFEST_URL")
),
tar_target(
    name = pinboard_src,
    command = pins::board_url(manifest_url, cache = cache_path, use_cache_on_failure = TRUE)
),
tar_target(
    name = pin_names,
    command = pins::pin_list(pinboard_src)[grepl("data", pins::pin_list(pinboard_src))]
),
tar_target(
    name = pin_cache,
    command = pins::pin_download(pinboard_src, name = pin_names),
    pattern = map(pin_names), 
    iteration = "list"
),
tar_target(
    name = pin_files,
    command = convert_pins(pinboard_src, pin_names)
)
)
```