---
title: "Process raw data"
subtitle: "`data_process` subproject."
html:
    code-fold: true
    number-sections: true
---


## Setup

### Set environment for subproject

```{r}
#| label: set_project
Sys.setenv(TAR_PROJECT = "data_process")
```

### Initialize `targets` script

```{r}
#| label: setup
library(targets)
tar_unscript(script = "_data_process.R")
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


### Define `targets` globals

We first define some global options/functions common to all targets.

```{r}
#| engine: targets
#| label: globals
#| tar_globals: true

# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
tar_option_set(packages = packages())
```

## Targets

```{r}
#| engine: targets
#| label: register_data
list(
  tar_target(
    name = csf_data_raw,
    command = targets::tar_read(csf_data_raw, store = "_data_get"),
    format = "qs" 
  ),
  tar_target(
    name = anr_data_raw,
    command = targets::tar_read(anr_data_raw, store = "_data_get"),
    format = "qs" 
  ),
  tar_target(
    name = snsf_data_raw,
    command = targets::tar_read(snsf_data_raw, store = "_data_get"),
    format = "qs" 
  ),
  tar_target(
    name = eu_data_raw,
    command = targets::tar_read(eu_data_raw, store = "_data_get"),
    format = "qs" 
  )
)
```

## Reset subproject
```{r}
#| label: unset_project
Sys.setenv(TAR_PROJECT = "main")
```