---
title: "TOPFUN targets pipeline"
output: 
  html_document:
      toc: true
      code_folding: hide
---

## Setup

```{r setup, include = FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
options(tidyverse.quiet = TRUE)

library(targets)
library(tarchetypes)
library(here)
tar_unscript()
```


## Functions and packages

Load required libraries and custom functions.

```{targets globals, tar_globals = TRUE}
source(here::here("R", "packages.R"))
# lapply(packages, library, character.only = TRUE)
tar_option_set(packages = packages,
               garbage_collection = TRUE)
# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
```


### Import of raw data 

This section downloads the raw data content from remote sources.

The data are loaded so as to be used in the pipeline.

```{targets data_import}

list(
    
    # Download CSF data
    
    # tar_cue(mode = "never") means the target runs only when the targets cache is empty
    # download_data() checks if file exists in the location and skips the download
    # if that is the case. This means that for a full refresh of the project,  
    # data should be manually removed from the raw_data folder and the target should be
    # invalidate with targets::tar_invalidate(data_csf_download)

    
    # Download CSF dataset
    tar_target(
        data_csf_download,
        download_data(
            url = "https://owncloud.cesnet.cz/index.php/s/HIm7FEYQIMfoBuu/download",
            data_file = here("data", 
                             "data_raw", 
                             "czech_science_foundation.tsv")
            ),
        format = "file",
        cue = tar_cue(mode = "never")
    ),
   

    # Read CSF data as an R object
    tar_target(
        data_csf,
        read_tsv(data_csf_download)
    ),
    
    # Download ANR dataset
    tar_target(
        data_anr_download,
        download_data(
            url = "https://data.enseignementsup-recherche.gouv.fr//explore/dataset/fr-esr-aap-anr-projets-retenus-participants-identifies/download",
            data_file = here("data", 
                             "data_raw", 
                             "agence_nationale_recherche.csv")
            ),
        format = "file",
        cue = tar_cue(mode = "never")
    ),
    
    # Read ANR data as an R object
    tar_target(
        data_anr,
        read_delim(data_anr_download,
                   delim = ";",
                   locale = locale("fr",
                                  decimal_mark = "."))
    ),
    
    # Download CORDIS dataset
    
    tar_target(
        data_erc_download,
        download_data(
            url = "https://cordis.europa.eu/data/cordis-fp7projects.csv",
        data_file = here("data", 
                             "data_raw", 
                             "cordis-fp7projects.csv")
        ),
        format = "file",
        cue = tar_cue(mode = "never")
        
    ),
    
    # Read ERC data as an R object
    tar_target(
        data_erc,
        read_csv2(data_erc_download)
    )
    
)


```

### Data documentation

```{targets data_documentation}
    # Make documentation for data
    # moving rendered document to `docs` folder
    # temporary hack until output path can be specified directly 
    # in `tar_render`
    tarchetypes::tar_render(
        data_documentation,
        path = "Rmd/data_documentation.Rmd", 
        params = list(targets_store = "_targets")
    )
```


## Language detection

Here we ensure that the text data - project abstracts - that we work with are either in English or in French. Automatic language detection is used for this purpose. In addition, French data are automatically translated into English. 

```{targets lang}

list(
    
    tar_target(anr_lang_desc,
               detect_lang(data = data_anr,
                           id = "code_du_projet",
                           col = "resume",
                           whitelist = c("fra", "eng"),
                           keep_all = FALSE
                           )
               ),
    
    tar_target(csf_lang_desc,
               detect_lang(data = data_csf,
                           id = "project_code",
                           col = "abstract",
                           whitelist = c("ces", "eng"),
                           keep_all = FALSE
                           )
    ),
    
    tar_target(data_anr_for_translation,
        data_anr %>% 
            filter(code_du_projet %in% 
                              (anr_lang_desc %>% 
                              filter(resume_lang == "fra") %>% 
                              pull(code_du_projet))
                          ) %>% 
            mutate(source_text = 
                       paste(titre,
                             resume, 
                             sep = ". "
                             )
                   ) %>% 
            select(code_du_projet,
                   source_text
                   )
               ),
    
    tar_target(data_anr_translated,
               run_cubbitt_api(
                   data_anr_for_translation %>% 
                       slice_head(n = 5),# test on sample
                   col = "source_text",
                   new_col = "resume_tr"),
               cue = tar_cue("never")
               )
    
    
)

```



## Comparative dataset

From the full datasets, we select only the projects that can be meaningfully compared across different (inter)national contexts. The criteria are:

- overlap in time
- overlap in the type of projects
    - i.e. we select only only investigator-initiated projects and distinguish junior and advanced schemes.
    
A single, unified dataset for comparison is produced.
    
Basic descriptive statistics are calculated and plotted.

```{targets compare}

list(
    
    tar_target(data_anr_sel,
               filter_anr(data_anr)
               ),
    
    tar_target(data_csf_sel,
               filter_csf(data_csf)
               ),
    
    tar_target(data_erc_sel,
               filter_erc(data_erc)
               ),
    
    tar_target(data_all,
               combine_anr_csf(data_anr_sel,
                               data_csf_sel,
                               data_erc_sel)),
    # number of projects
    tar_target(data_all_type_plot,
               plot_data_all_type(data_all)),
    # funding amounts - absolute
    tar_target(data_all_funding_plot,
               plot_data_all_funding(data_all)),
    # funding amounts - normalized by number of projects
    tar_target(data_all_mean_plot,
               plot_data_all_mean(data_all)),
    # funding amounts - normalized by number of projects and their duration in years
    tar_target(data_all_mean_yearlyplot,
               plot_data_all_mean_yearly(data_all))
    
    
    
    
)
```

## Text data for export

This section prepares text data to be exported as inputs for topic modeling. It uses only the projects that were selected for the comparative dataset.

```{targets text_export}

list(
    
    
    tar_target(text_export_anr,
               export_text_anr(data_anr_sel,
                               anr_lang_desc),
               format = "file"),
    
    tar_target(text_export_csf,
               export_text_csf(data_csf_sel,
                               csf_lang_desc),
               format = "file"),
    
    tar_target(text_export_erc,
               export_text_erc(data_erc_sel),
               format = "file")
    
    
    
)

```

## Load topic models

The following section contains topic models that were calculated on the basis of text exported in the text export section.

```{targets topic_models}

list(
    
    # ANR
    tar_target(topic_model_anr_data,
               download_data(
            url = "https://owncloud.cesnet.cz/index.php/s/riibpYmTDiYVHZO/download",
            data_file = here("data", 
                             "data_raw", 
                             "topic_model_202109292040.qs")
            ),
        format = "file",
        cue = tar_cue(mode = "never")
    ),
    
    tar_target(topic_model_anr,
               qread(topic_model_anr_data),
               format = "qs"),
    
    # CSF
    tar_target(topic_model_csf_data,
               download_data(
            url = "https://owncloud.cesnet.cz/index.php/s/a3ZqLZ2ljfJtoHo/download",
            data_file = here("data", 
                             "data_raw", 
                             "topic_model_202109300955.qs")
            ),
        format = "file",
        cue = tar_cue(mode = "never")
    ),
    
    tar_target(topic_model_csf,
               qread(topic_model_csf_data),
               format = "qs"),
    
    # ERC
    tar_target(topic_model_erc_data,
               download_data(
            url = "https://owncloud.cesnet.cz/index.php/s/WBMOFhftZDuWUhD/download",
            data_file = here("data", 
                             "data_raw", 
                             "topic_model_202109301159.qs")
            ),
        format = "file",
        cue = tar_cue(mode = "never")
    ),
    
    tar_target(topic_model_erc,
               qread(topic_model_erc_data),
               format = "qs")
    
)

```

## Data overview report

This section produces an initial report on the available data with basic descriptive statistics.

```{targets data_overview}

list(
    tarchetypes::tar_render(data_overview,
                            here::here("Rmd/data_overview.Rmd"),
                            params = list(targets_store = "_targets"))
)

```

