---
title: "Run topic modeling"
format: html
---

This subproject initializes pinboard required for the default `targets` project.

## Setup

### Targets environment for subproject

```{r}
#| label: define_project
#| include: false
Sys.setenv(TAR_PROJECT = "topmodel")
```

### Targets script setup

```{r}
#| label: setup
#| include: false
library(targets)
tar_unscript(script = "_topmodel.R")
knitr::opts_chunk$set(collapse = TRUE, comment = "#>")
```


### Targets globals

We first define some global options/functions common to all targets.

```{r}
#| engine: targets
#| label: globals
#| tar_globals: true

# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
tar_option_set(packages = packages())
```

## Read text data

First we register the source pinboard for the input data.
```{r}
#| engine: targets
#| label: pinboard_import
list(
    tar_target(
        name = pins,
        command = tar_read("pin_files", store = "_pinboard")
    )
)
```

```{r}
#| engine: targets
#| label: read_text
list(
tar_target(
    name = raw_corpus,
    command = read_corpus(pins)
)
)
```