---
title: "Process raw data"
subtitle: "`data_process` subproject."
html:
    code-fold: true
    number-sections: true
---


## Setup

### Set environment for subproject

```{r}
#| label: set_project
Sys.setenv(TAR_PROJECT = "data_process")
```

### Initialize `data_process` script

```{r}
#| label: setup
library(targets)
tar_unscript()
knitr::opts_chunk$set(tar_script = "_data_process.R", collapse = TRUE, comment = "#>")
```


### Define `data_process` globals

We first define some global options/functions common to all targets.

```{r}
#| engine: targets
#| label: globals
#| tar_globals: true

# read custom functions
lapply(list.files(here::here("R"), full.names = TRUE), source)
tar_option_set(packages = packages())
```

## Targets for `data_process`

First we register raw data files.
```{r}
#| engine: targets
#| label: register_data
list(
  tar_target(
    name = input_data_files,
    command = targets::tar_read(input_data_files, store = "_store/_data_input"),
    format = "file",
    cue = tar_cue("always")
  )
)
```

### ANR read
```{r}
#| engine: targets
#| label: anr_data
list(
  tar_target(
    name = anr_data_raw_2010,
    command = read_input_anr(input_data_files, file_name = "anr_2010.csv"),
    format = "qs"
  ),
  tar_target(
    name = anr_data_raw_2009,
    command = read_input_anr(input_data_files, file_name = "anr_2009.csv"),
    format = "qs"
  ),
  tar_target(
    name = anr_data_raw_2010_p,
    command = read_input_anr(input_data_files, file_name = "anr_2010_p.csv"),
    format = "qs"
  ),
  tar_target(
    name = anr_data_raw_2009_p,
    command = read_input_anr(input_data_files, file_name = "anr_2009_p.csv"),
    format = "qs"
  ),
  tar_target(
    name = anr_data_projects,
    command = dplyr::bind_rows(
      anr_data_raw_2010,
      anr_data_raw_2009
    ),
    format = "qs"
  ),
  tar_target(
    name = anr_data_institutions,
    command = dplyr::bind_rows(
      anr_data_raw_2010_p,
      anr_data_raw_2009_p
    ),
    format = "qs"
  ),
  tar_target(
    name = anr_data_raw,
    command = anr_data_projects |> 
    dplyr::left_join(anr_data_institutions,
    by = "project_id"),
    format = "qs"
  )
)
```

### ANR filter

```{r}
#| engine: targets
#| label: anr_filter
list(
  tar_target(
    name = anr_data,
    command = filter_anr(anr_data_raw, years = c(2012, 2022)),
    format = "qs"
  )
)
```

### ERC read

```{r}
#| engine: targets
#| label: eu_data
list(
  tar_target(
    name = eu_data,
    command = read_input_eu(input_data_files, file_name = c(
      "eu_fp7.csv",
      "eu_horizon.csv",
      "eu_europe.csv"
    )),
    format = "qs"
  ),
  tar_target(
    name = erc_data_raw,
    command = read_input_erc(input_data_files, file_name = "erc_dashboard.tsv"),
    format = "qs"
  )
)
```

### ERC filter

```{r}
#| engine: targets
#| label: erc_filter
list(
  tar_target(
    name = erc_data,
    command = filter_erc(erc_data_raw, years = c(2012, 2022)),
    format = "qs"
  )
)
```

### SNSF read

```{r}
#| engine: targets
#| label: snsf_data
list(
  tar_target(
    name = snsf_data_raw,
    command = read_input_snsf(input_data_files, file_name = "snsf.csv"),
    format = "qs"
  )
)
```

### SNSF filter

```{r}
#| engine: targets
#| label: snsf_filter
list(
  tar_target(
    name = snsf_data,
    command = filter_snsf(snsf_data_raw, years = c(2012, 2022)),
    format = "qs"
  )
)
```

### DFG read

```{r}
#| engine: targets
#| label: dfg_data
list(
  tar_target(
    name = dfg_data_raw,
    command = read_input_dfg(input_data_files, file_name = "dfg_projects.tsv"),
    format = "qs"
  )
)
```

### DFG filter

```{r}
#| engine: targets
#| label: dfg_filter
list(
  tar_target(
    name = dfg_data,
    command = filter_dfg(dfg_data_raw, years = c(2012, 2022)),
    format = "qs"
  )
)
```


## Reset subproject
```{r}
#| label: unset_project
Sys.setenv(TAR_PROJECT = "main")
```